"""Add comment field to LetterBlock

Revision ID: e1f5ef87cf46
Revises: 171e85881191
Create Date: 2025-04-20 11:46:46.826220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f5ef87cf46'
down_revision = '171e85881191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letter_block', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
